import type { ModeMeta, ShoppingModeId } from "./types";

/**
 * Client-safe display + routing metadata for every ShopLens mode. This is the
 * single source of truth the mode picker, badges, and heuristic router read.
 * No server-only imports — safe for client components.
 */

export const MODE_META: Record<ShoppingModeId, ModeMeta> = {
  gift: {
    id: "gift",
    name: "GiftLens",
    short: "Gift",
    tagline: "Describe the person — get thoughtful, buyable gifts.",
    icon: "Gift",
    accent: "plum",
    resultKind: "picks",
    examplePrompt:
      "Anniversary gift for my partner who loves coffee and pottery, dislikes clutter, budget ₹5,000",
    keywords: ["gift", "present", "birthday", "anniversary", "housewarming", "wedding", "for my", "surprise"],
    routeExamples: [
      "a birthday gift for my sister who loves hiking",
      "anniversary present for my partner, budget ₹5000",
      "thoughtful gift for a new parent",
    ],
    refinements: [
      "More personal", "More unique", "More practical", "More sentimental",
      "Safer choice", "Lower budget", "Premium option", "Different category",
    ],
    badges: [
      { key: "best_match", label: "Best Match", blurb: "Highest overall fit" },
      { key: "delight_pick", label: "Delight Pick", blurb: "Surprising but defensible" },
      { key: "safe_pick", label: "Safe Pick", blurb: "Broadly appealing, low-risk" },
      { key: "more", label: "Great match", blurb: "Strong overall fit" },
    ],
    requiresApproval: false,
  },
  swap: {
    id: "swap",
    name: "SwapLens",
    short: "Swap",
    tagline: "Paste a product — find a better-fitting alternative.",
    icon: "ArrowLeftRight",
    accent: "plum",
    resultKind: "picks",
    examplePrompt: "I like this lamp, find something similar under ₹5,000 that ships to India",
    keywords: ["alternative", "similar to", "cheaper", "instead of", "like this", "dupe", "swap", "replace", "better version"],
    routeExamples: [
      "find something similar to this but cheaper",
      "a more sustainable alternative to this jacket",
      "same style lamp under ₹5000 from another seller",
    ],
    refinements: [
      "Less expensive", "More sustainable", "Different color", "Another seller",
      "Similar aesthetic", "Higher rated", "Premium option",
    ],
    badges: [
      { key: "best_match", label: "Closest match", blurb: "Nearest to the original" },
      { key: "delight_pick", label: "Different angle", blurb: "Similar vibe, fresh take" },
      { key: "safe_pick", label: "Safer swap", blurb: "Dependable alternative" },
      { key: "more", label: "Also worth a look", blurb: "Related alternative" },
    ],
    requiresApproval: false,
  },
  skincare: {
    id: "skincare",
    name: "RoutineLens",
    short: "Skincare",
    tagline: "Build a simple, preference-based skincare routine.",
    icon: "Droplets",
    accent: "plum",
    resultKind: "plan",
    examplePrompt:
      "My skin feels dry and sensitive. Simple routine under ₹3,000, no fragrance.",
    keywords: ["skin", "skincare", "routine", "cleanser", "moisturizer", "serum", "sunscreen", "fragrance-free", "dry skin", "oily", "sensitive"],
    routeExamples: [
      "a simple skincare routine for dry sensitive skin",
      "fragrance-free morning routine under ₹3000",
      "build me a minimal skincare routine",
    ],
    refinements: [
      "Simplify the routine", "Lower the budget", "Fragrance-free only",
      "Avoid a brand", "Different texture", "Add evening step",
    ],
    badges: [],
    requiresApproval: true,
    educational: true,
  },
  style: {
    id: "style",
    name: "StyleLens",
    short: "Outfit",
    tagline: "Turn an occasion + vibe into a complete, coordinated look.",
    icon: "Shirt",
    accent: "gold",
    resultKind: "plan",
    examplePrompt: "Smart-casual outfit for a first date, confident but not overdressed, under ₹12,000",
    keywords: ["outfit", "look", "wear", "style", "wardrobe", "streetwear", "smart-casual", "dress code", "what to wear"],
    routeExamples: [
      "build me a smart-casual first-date outfit",
      "a minimalist streetwear look under ₹12000",
      "an outfit that works with my black sneakers",
    ],
    refinements: [
      "Make it bolder", "More minimal", "More formal", "More relaxed",
      "Reduce total price", "Change the color palette", "Replace one piece",
    ],
    badges: [],
    requiresApproval: true,
  },
  nutrition: {
    id: "nutrition",
    name: "FuelLens",
    short: "Nutrition",
    tagline: "Organize a goal-based grocery basket around your preferences.",
    icon: "Salad",
    accent: "plum",
    resultKind: "plan",
    examplePrompt:
      "Convenient vegetarian basket to hit my protein target, ₹4,500 weekly, little time to cook",
    keywords: ["protein", "diet", "meal", "grocery", "basket", "nutrition", "vegetarian", "vegan", "high-protein", "snack", "calorie"],
    routeExamples: [
      "a convenient high-protein vegetarian basket",
      "weekly grocery basket for a fitness goal, ₹4500",
      "food-first protein shopping plan",
    ],
    refinements: [
      "Food-first only", "More convenient", "Lower the budget",
      "Vegetarian", "Vegan", "Avoid a food", "Add a snack",
    ],
    badges: [],
    requiresApproval: true,
    educational: true,
  },
  room: {
    id: "room",
    name: "SpaceLens",
    short: "Room",
    tagline: "Turn a room's desired mood into a coordinated shopping bundle.",
    icon: "Sofa",
    accent: "gold",
    resultKind: "plan",
    examplePrompt: "Make my small bedroom feel warmer and more Scandinavian for under ₹20,000",
    keywords: ["room", "bedroom", "living room", "decor", "space", "interior", "lighting", "cozy", "scandinavian", "makeover"],
    routeExamples: [
      "make my small bedroom feel warmer for ₹20000",
      "a cozy minimalist living-room refresh",
      "scandinavian bedroom bundle under budget",
    ],
    refinements: [
      "Make it bolder", "More minimal", "Warmer palette", "Reduce total price",
      "Swap the lighting", "Different textile", "Add a plant",
    ],
    badges: [],
    requiresApproval: true,
  },
  travel: {
    id: "travel",
    name: "TripLens",
    short: "Travel",
    tagline: "Build a compact packing kit for a specific trip.",
    icon: "Luggage",
    accent: "plum",
    resultKind: "plan",
    examplePrompt: "Iceland for 7 days in October — compact kit for hiking and city sightseeing",
    keywords: ["trip", "travel", "packing", "pack", "kit", "vacation", "hiking trip", "luggage", "going to"],
    routeExamples: [
      "a compact packing kit for Iceland in October",
      "what to pack for a week of hiking",
      "build the rest of my travel kit around this jacket",
    ],
    refinements: [
      "Lighter/compact", "Warmer layers", "Reduce total price",
      "Add day bag", "Add toiletries", "Different climate",
    ],
    badges: [],
    requiresApproval: true,
  },
  hobby: {
    id: "hobby",
    name: "StartLens",
    short: "Hobby kit",
    tagline: "Assemble a beginner starter kit for a new hobby.",
    icon: "Palette",
    accent: "gold",
    resultKind: "plan",
    examplePrompt: "Beginner pour-over coffee kit under ₹8,000",
    keywords: ["beginner", "starter", "kit", "start", "hobby", "learn", "get into", "watercolor", "gardening", "home workout"],
    routeExamples: [
      "a beginner pour-over coffee kit under ₹8000",
      "starter watercolor kit for an adult beginner",
      "help me start balcony gardening",
    ],
    refinements: [
      "Basic kit", "Balanced kit", "Premium kit", "Reduce total price",
      "Essentials only", "Add an upgrade", "Small-space friendly",
    ],
    badges: [],
    requiresApproval: true,
  },
  lifestage: {
    id: "lifestage",
    name: "NewChapter",
    short: "Life stage",
    tagline: "Phase a life-transition shopping plan by priority.",
    icon: "KeyRound",
    accent: "plum",
    resultKind: "plan",
    examplePrompt: "Moving into my first apartment with ₹30,000 for the essentials",
    keywords: ["moving", "first apartment", "dorm", "new job", "new parent", "new home", "university", "setting up", "home office"],
    routeExamples: [
      "moving into my first apartment, ₹30000 for essentials",
      "setting up a dorm room",
      "a first-kitchen starter set",
    ],
    refinements: [
      "Must-haves only", "Reduce total price", "Add first-month items",
      "Small space", "Different room", "More budget-friendly",
    ],
    badges: [],
    requiresApproval: true,
  },
  occasion: {
    id: "occasion",
    name: "ReadyLens",
    short: "Occasion",
    tagline: "A complete shopping plan to get ready for an occasion.",
    icon: "PartyPopper",
    accent: "gold",
    resultKind: "plan",
    examplePrompt: "Get me ready for a beach wedding",
    keywords: ["get ready for", "prepare", "host", "dinner party", "interview", "date night", "festival", "occasion", "everything i need"],
    routeExamples: [
      "get me ready for a beach wedding",
      "everything I need for a first job interview",
      "a host kit for a dinner party",
    ],
    refinements: [
      "More formal", "More casual", "Reduce total price", "Add a host gift",
      "Swap a category", "Different vibe",
    ],
    badges: [],
    requiresApproval: true,
  },
};

export const ALL_MODE_META: ModeMeta[] = Object.values(MODE_META);
